### ISSUE TITLE
add arcgis wrapper

### ISSUE THREAD

**Issue by smnorris** [bcgov/FIT_changedetector#3]
Enable calling script from arcgis toolbox on GTS. 
To do this, with a subprocess:
- activate a geopandas conda env (required for geopandas 1.0)
- call the script

tool should:
- support all parameters
- pipe stdout from the subprocess to the arcgis logging framework

**Comment by smnorris** [comment]
https://github.com/bcgov/FIT_changedetector/blob/main/src/fit_changedetector/arcgis_wrapper.py

**Comment by smnorris** [comment]
Activating the environment and running the script at the command line works fine, but trying to run the wrapper script gives this error:
```
Error processing line 1 of P:\corp\python3918\Lib\site-packages\ArcGISPro.pth:

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen site>", line 206, in addpackage
  File "<string>", line 1, in <module>
  File "P:\corp\python3918\Lib\site-packages\arcpy_init.py", line 6, in <module>
    import re
  File "P:\corp\python3918\Lib\re.py", line 125, in <module>
    import sre_compile
  File "P:\corp\python3918\Lib\sre_compile.py", line 17, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
           ^^^^^^^^^^^^^^^^^^^
AssertionError: SRE module mismatch

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in exec_module
  File "<frozen site>", line 635, in <module>
  File "<frozen site>", line 622, in main
  File "<frozen site>", line 405, in addsitepackages
  File "<frozen site>", line 247, in addsitedir
  File "<frozen site>", line 216, in addpackage
  File "P:\corp\python3918\Lib\traceback.py", line 5, in <module>
    import linecache
  File "P:\corp\python3918\Lib\linecache.py", line 11, in <module>
    import tokenize
  File "P:\corp\python3918\Lib\tokenize.py", line 32, in <module>
    import re
  File "P:\corp\python3918\Lib\re.py", line 125, in <module>
    import sre_compile
  File "P:\corp\python3918\Lib\sre_compile.py", line 17, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
           ^^^^^^^^^^^^^^^^^^^
AssertionError: SRE module mismatch
```

**Comment by smnorris** [comment]
same erro
 if attempting to call the script via `subprocess` in the ArcGIS python window:
```
result = subprocess.run(
    f"CALL conda.bat deactivate && conda activate {ENV} && changedetector --help",
    shell=True,
    capture_output=True,
    text=True,
)
result.stderr
'Error processing line 1 of P:\\corp\\python3918\\Lib\\site-packages\\ArcGISPro.pth:\n\nFatal Python error: init_import_site: Failed to import the site module\nPython runtime state: initialized\nTraceback (most recent call last):\n  File "<frozen site>", line 206, in addpackage\n  File "<string>", line 1, in <module>\n  File "P:\\corp\\python3918\\Lib\\site-packages\\arcpy_init.py", line 6, in <module>\n    import re\n  File "P:\\corp\\python3918\\Lib\\re.py", line 125, in <module>\n    import sre_compile\n  File "P:\\corp\\python3918\\Lib\\sre_compile.py", line 17, in <module>\n    assert _sre.MAGIC == MAGIC, "SRE module mismatch"\n           ^^^^^^^^^^^^^^^^^^^\nAssertionError: SRE module mismatch\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked\n  File "<frozen importlib._bootstrap>", line 1176, in exec_module\n  File "<frozen site>", line 635, in <module>\n  File "<frozen site>", line 622, in main\n  File "<frozen site>", line 405, in addsitepackages\n  File "<frozen site>", line 247, in addsitedir\n  File "<frozen site>", line 216, in addpackage\n  File "P:\\corp\\python3918\\Lib\\traceback.py", line 5, in <module>\n    import linecache\n  File "P:\\corp\\python3918\\Lib\\linecache.py", line 11, in <module>\n    import tokenize\n  File "P:\\corp\\python3918\\Lib\\tokenize.py", line 32, in <module>\n    import re\n  File "P:\\corp\\python3918\\Lib\\re.py", line 125, in <module>\n    import sre_compile\n  File "P:\\corp\\python3918\\Lib\\sre_compile.py", line 17, in <module>\n    assert _sre.MAGIC == MAGIC, "SRE module mismatch"\n           ^^^^^^^^^^^^^^^^^^^\nAssertionError: SRE module mismatch\n'
```

**Comment by smnorris** [comment]
Reverting to geopandas 0.14.4 until arcgis is upgraded on the server is probably the simplest fix.

**Comment by smnorris** [comment]
Downgrading to 0.14.4 is not that simple - adding the missing required function `set_precision` is straightforward but io is fairly different, v1 uses `pyogrio` and v0.14 uses `fiona`.  This will take time to debug.

**Comment by smnorris** [comment]
HOLD ON - geopandas v1.0.1 does not require Python 10. This should be installable to the default environment, making things much smoother.
