### ISSUE TITLE
Shapefiles comparison: Unsupported geometry type error

### ISSUE THREAD

**Issue by andershopperstead** [bcgov/FIT_changedetector#33]
Start Time: December 2, 2024 9:44:05 AM
2024-12-02 09:44:05,500 - root - INFO - Script tool parameters: {'debug': False,
 'drop_null_geometry': True,
 'dump_inputs': False,
 'fields': [],
 'hash_fields': [],
 'hash_key': 'fcd_hash_id',
 'ignore_fields': [],
 'new_fc': 'W:\\ilmb\\dss\\dss_workarea\\_contractors\\sinorris\\FIT_changedetector\\tests\\test_2024_11_29_Nanaimo\\RCL_NoZeroGID_2024.shp',
 'original_fc': 'W:\\ilmb\\dss\\dss_workarea\\_contractors\\sinorris\\FIT_changedetector\\tests\\test_2024_11_29_Nanaimo\\RCL_NoZeroGID_2020.shp',
 'out_folder': 'W:\\ilmb\\dss\\dss_workarea\\_contractors\\sinorris\\FIT_changedetector\\tests\\test_2024_11_29_Nanaimo',
 'precision': 1.0,
 'primary_key': ['GID_Long'],
 'suffix_a': 'original',
 'suffix_b': 'new'}
2024-12-02 09:44:05,501 - root - INFO - Output file: W:\ilmb\dss\dss_workarea\_contractors\sinorris\FIT_changedetector\tests\test_2024_11_29_Nanaimo\changedetector_20241202_0944.gdb
2024-12-02 09:44:06,488 - fit_changedetector.diff - INFO - NEW: 0 records
2024-12-02 09:44:06,489 - fit_changedetector.diff - INFO - DELETED: 29 records
2024-12-02 09:44:07,045 - fit_changedetector.diff - INFO - MODIFIED_BOTH: 57 records
2024-12-02 09:44:07,318 - fit_changedetector.diff - INFO - MODIFIED_ATTR: 3804 records
Unsupported geometry type
Failed script changedetector...
Failed to execute (changedetector).

**Comment by smnorris** [comment]
```
import geopandas
import fit_changedetector as fcd

df_a = geopandas.read_file("tmp/issue33/RCL_NoZeroGID_2020.shp")
df_b = geopandas.read_file("tmp/issue33/RCL_NoZeroGID_2024.shp")

diff = fcd.gdf_diff(df_a, df_b, "GID_Long")

diff["MODIFIED_ATTR"].to_file("test.gdb", driver="OpenFileGDB")

Traceback (most recent call last):
  File "pyogrio/_io.pyx", line 2193, in pyogrio._io.create_ogr_dataset_layer
  File "pyogrio/_err.pyx", line 183, in pyogrio._err.exc_wrap_pointer
pyogrio._err.CPLE_NotSupportedError: Unsupported geometry type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/snorris/.vscode/extensions/ms-python.python-2024.20.0-darwin-arm64/python_files/python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
  File "/Users/snorris/Projects/repo/fit_changedetector/.venv/lib/python3.13/site-packages/geopandas/geodataframe.py", line 1536, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snorris/Projects/repo/fit_changedetector/.venv/lib/python3.13/site-packages/geopandas/io/file.py", line 686, in _to_file
    _to_file_pyogrio(df, filename, driver, schema, crs, mode, metadata, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snorris/Projects/repo/fit_changedetector/.venv/lib/python3.13/site-packages/geopandas/io/file.py", line 748, in _to_file_pyogrio
    pyogrio.write_dataframe(df, filename, driver=driver, metadata=metadata, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snorris/Projects/repo/fit_changedetector/.venv/lib/python3.13/site-packages/pyogrio/geopandas.py", line 662, in write_dataframe
    write(
    ~~~~~^
        path,
        ^^^^^
...
  File "pyogrio/_io.pyx", line 2307, in pyogrio._io.ogr_write
  File "pyogrio/_io.pyx", line 2207, in pyogrio._io.create_ogr_dataset_layer
pyogrio.errors.DataLayerError: Unsupported geometry type
```

Dataframe giving the issue has two geometry types:

```
>> diff["MODIFIED_ATTR"].geometry.geom_type.unique()

['LineString' 'MultiLineString']
```

**Comment by smnorris** [comment]
It is the source, I guess shapefiles support mixed multi/single part types.

```
df_a.geometry.geom_type.unique()
df_b.geometry.geom_type.unique()
```

**Comment by smnorris** [comment]
It is a common issue, no problem silently handling a mix of single/multipart

**Comment by smnorris** [comment]
Which do you prefer when a mix is found - aggregate singles to multi or "explode" multis to single?

**Comment by smnorris** [comment]
Actually, ignore that question. We can't explode, the provided primary key will no longer be unique.  Has to be promoting the singleparts to multipart .

**Comment by andershopperstead** [comment]
Do they all have to be one type for the comparison to work?

**Comment by smnorris** [comment]
No, the comparison works fine - geopandas will accept mixed types. 
Issue is the .gdb driver - a feature class can only contain one type of geometry (I'm presuming). 
Some formats are more particular than others, postgis does this too.

**Comment by andershopperstead** [comment]
Right - it's the output. Sorry - didn't connect the dots. Promoting Singlepart to Multipart is the path to go - Thank you!

**Comment by andershopperstead** [comment]
I'm in favour of anything that discourages the use of shapefiles, so definitely stick to the GDB output. Die-hard shapefile users can always go backwards if they are that stubborn.
